//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttpTraderTest.TradingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TradingService.ITradingService")]
    public interface ITradingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingService/Login", ReplyAction="http://tempuri.org/ITradingService/LoginResponse")]
        string Login(string loginId, string password, string companyName, string language, int versionCode, string deviceInfo, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingService/GetInitData", ReplyAction="http://tempuri.org/ITradingService/GetInitDataResponse")]
        string GetInitData(string sessionId, string accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingService/GetComand", ReplyAction="http://tempuri.org/ITradingService/GetComandResponse")]
        string GetComand(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingService/LoginOut", ReplyAction="http://tempuri.org/ITradingService/LoginOutResponse")]
        string LoginOut(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingService/Test", ReplyAction="http://tempuri.org/ITradingService/TestResponse")]
        string Test();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITradingServiceChannel : HttpTraderTest.TradingService.ITradingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TradingServiceClient : System.ServiceModel.ClientBase<HttpTraderTest.TradingService.ITradingService>, HttpTraderTest.TradingService.ITradingService {
        
        public TradingServiceClient() {
        }
        
        public TradingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TradingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string loginId, string password, string companyName, string language, int versionCode, string deviceInfo, string version) {
            return base.Channel.Login(loginId, password, companyName, language, versionCode, deviceInfo, version);
        }
        
        public string GetInitData(string sessionId, string accountId) {
            return base.Channel.GetInitData(sessionId, accountId);
        }
        
        public string GetComand(string sessionId) {
            return base.Channel.GetComand(sessionId);
        }
        
        public string LoginOut(string sessionId) {
            return base.Channel.LoginOut(sessionId);
        }
        
        public string Test() {
            return base.Channel.Test();
        }
    }
}
