//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17379.
// 
#pragma warning disable 1591

namespace ConsoleApplication13.FaxEmailService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FaxEmailServiceSoap", Namespace="http://tempuri.org/")]
    public partial class FaxEmailService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NotifyOrderExecutedOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyResetStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyRiskLevelChangedOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyBalanceChangedOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyPasswordResetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FaxEmailService() {
            this.Url = global::ConsoleApplication13.Properties.Settings.Default.ConsoleApplication13_FaxEmailService_FaxEmailService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NotifyOrderExecutedCompletedEventHandler NotifyOrderExecutedCompleted;
        
        /// <remarks/>
        public event NotifyResetStatementCompletedEventHandler NotifyResetStatementCompleted;
        
        /// <remarks/>
        public event NotifyRiskLevelChangedCompletedEventHandler NotifyRiskLevelChangedCompleted;
        
        /// <remarks/>
        public event NotifyBalanceChangedCompletedEventHandler NotifyBalanceChangedCompleted;
        
        /// <remarks/>
        public event NotifyPasswordResetCompletedEventHandler NotifyPasswordResetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyOrderExecuted", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void NotifyOrderExecuted(System.Guid orderId) {
            this.Invoke("NotifyOrderExecuted", new object[] {
                        orderId});
        }
        
        /// <remarks/>
        public void NotifyOrderExecutedAsync(System.Guid orderId) {
            this.NotifyOrderExecutedAsync(orderId, null);
        }
        
        /// <remarks/>
        public void NotifyOrderExecutedAsync(System.Guid orderId, object userState) {
            if ((this.NotifyOrderExecutedOperationCompleted == null)) {
                this.NotifyOrderExecutedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyOrderExecutedOperationCompleted);
            }
            this.InvokeAsync("NotifyOrderExecuted", new object[] {
                        orderId}, this.NotifyOrderExecutedOperationCompleted, userState);
        }
        
        private void OnNotifyOrderExecutedOperationCompleted(object arg) {
            if ((this.NotifyOrderExecutedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyOrderExecutedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyResetStatement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void NotifyResetStatement(System.DateTime tradeDay) {
            this.Invoke("NotifyResetStatement", new object[] {
                        tradeDay});
        }
        
        /// <remarks/>
        public void NotifyResetStatementAsync(System.DateTime tradeDay) {
            this.NotifyResetStatementAsync(tradeDay, null);
        }
        
        /// <remarks/>
        public void NotifyResetStatementAsync(System.DateTime tradeDay, object userState) {
            if ((this.NotifyResetStatementOperationCompleted == null)) {
                this.NotifyResetStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyResetStatementOperationCompleted);
            }
            this.InvokeAsync("NotifyResetStatement", new object[] {
                        tradeDay}, this.NotifyResetStatementOperationCompleted, userState);
        }
        
        private void OnNotifyResetStatementOperationCompleted(object arg) {
            if ((this.NotifyResetStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyResetStatementCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyRiskLevelChanged", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void NotifyRiskLevelChanged(RiskLevelChangedInfo info) {
            this.Invoke("NotifyRiskLevelChanged", new object[] {
                        info});
        }
        
        /// <remarks/>
        public void NotifyRiskLevelChangedAsync(RiskLevelChangedInfo info) {
            this.NotifyRiskLevelChangedAsync(info, null);
        }
        
        /// <remarks/>
        public void NotifyRiskLevelChangedAsync(RiskLevelChangedInfo info, object userState) {
            if ((this.NotifyRiskLevelChangedOperationCompleted == null)) {
                this.NotifyRiskLevelChangedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyRiskLevelChangedOperationCompleted);
            }
            this.InvokeAsync("NotifyRiskLevelChanged", new object[] {
                        info}, this.NotifyRiskLevelChangedOperationCompleted, userState);
        }
        
        private void OnNotifyRiskLevelChangedOperationCompleted(object arg) {
            if ((this.NotifyRiskLevelChangedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyRiskLevelChangedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyBalanceChanged", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void NotifyBalanceChanged(BalanceInfo info) {
            this.Invoke("NotifyBalanceChanged", new object[] {
                        info});
        }
        
        /// <remarks/>
        public void NotifyBalanceChangedAsync(BalanceInfo info) {
            this.NotifyBalanceChangedAsync(info, null);
        }
        
        /// <remarks/>
        public void NotifyBalanceChangedAsync(BalanceInfo info, object userState) {
            if ((this.NotifyBalanceChangedOperationCompleted == null)) {
                this.NotifyBalanceChangedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyBalanceChangedOperationCompleted);
            }
            this.InvokeAsync("NotifyBalanceChanged", new object[] {
                        info}, this.NotifyBalanceChangedOperationCompleted, userState);
        }
        
        private void OnNotifyBalanceChangedOperationCompleted(object arg) {
            if ((this.NotifyBalanceChangedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyBalanceChangedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyPasswordReset", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void NotifyPasswordReset(PasswordResetInfo info) {
            this.Invoke("NotifyPasswordReset", new object[] {
                        info});
        }
        
        /// <remarks/>
        public void NotifyPasswordResetAsync(PasswordResetInfo info) {
            this.NotifyPasswordResetAsync(info, null);
        }
        
        /// <remarks/>
        public void NotifyPasswordResetAsync(PasswordResetInfo info, object userState) {
            if ((this.NotifyPasswordResetOperationCompleted == null)) {
                this.NotifyPasswordResetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyPasswordResetOperationCompleted);
            }
            this.InvokeAsync("NotifyPasswordReset", new object[] {
                        info}, this.NotifyPasswordResetOperationCompleted, userState);
        }
        
        private void OnNotifyPasswordResetOperationCompleted(object arg) {
            if ((this.NotifyPasswordResetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyPasswordResetCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RiskLevelChangedInfo {
        
        private System.Guid accountIDField;
        
        private string clientNameField;
        
        private string accountNameField;
        
        private string currencyCodeField;
        
        private double equityField;
        
        private double initialMarginField;
        
        private System.DateTime tradeDayField;
        
        private int riskLevelField;
        
        private string[] transactionCodesField;
        
        /// <remarks/>
        public System.Guid AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
            }
        }
        
        /// <remarks/>
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public double Equity {
            get {
                return this.equityField;
            }
            set {
                this.equityField = value;
            }
        }
        
        /// <remarks/>
        public double InitialMargin {
            get {
                return this.initialMarginField;
            }
            set {
                this.initialMarginField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TradeDay {
            get {
                return this.tradeDayField;
            }
            set {
                this.tradeDayField = value;
            }
        }
        
        /// <remarks/>
        public int RiskLevel {
            get {
                return this.riskLevelField;
            }
            set {
                this.riskLevelField = value;
            }
        }
        
        /// <remarks/>
        public string[] TransactionCodes {
            get {
                return this.transactionCodesField;
            }
            set {
                this.transactionCodesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PasswordResetInfo {
        
        private System.Guid customerIDField;
        
        private string loginNameField;
        
        private string passwordField;
        
        /// <remarks/>
        public System.Guid CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string LoginName {
            get {
                return this.loginNameField;
            }
            set {
                this.loginNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BalanceInfo {
        
        private System.Guid accountIDField;
        
        private string clientNameField;
        
        private string accountCodeField;
        
        private string currencyCodeField;
        
        private double amountField;
        
        private System.DateTime tradeDayField;
        
        private BalanceChangeSubject changeSubjectField;
        
        /// <remarks/>
        public System.Guid AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
            }
        }
        
        /// <remarks/>
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        public string AccountCode {
            get {
                return this.accountCodeField;
            }
            set {
                this.accountCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TradeDay {
            get {
                return this.tradeDayField;
            }
            set {
                this.tradeDayField = value;
            }
        }
        
        /// <remarks/>
        public BalanceChangeSubject ChangeSubject {
            get {
                return this.changeSubjectField;
            }
            set {
                this.changeSubjectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum BalanceChangeSubject {
        
        /// <remarks/>
        Deposit,
        
        /// <remarks/>
        Withdrawal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void NotifyOrderExecutedCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void NotifyResetStatementCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void NotifyRiskLevelChangedCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void NotifyBalanceChangedCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void NotifyPasswordResetCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591