//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionServerTester.TransactionServerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransactionServerService.IServerService")]
    public interface IServerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Place", ReplyAction="http://tempuri.org/IServerService/PlaceResponse")]
        iExchange.Common.TransactionError Place(string tranXml, bool placeByRiskMonitor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/PlaceByModel", ReplyAction="http://tempuri.org/IServerService/PlaceByModelResponse")]
        void PlaceByModel(Protocal.TransactionData tranData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Test", ReplyAction="http://tempuri.org/IServerService/TestResponse")]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetInitData", ReplyAction="http://tempuri.org/IServerService/GetInitDataResponse")]
        string GetInitData(System.Guid[] accountIds);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerServiceChannel : TransactionServerTester.TransactionServerService.IServerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerServiceClient : System.ServiceModel.ClientBase<TransactionServerTester.TransactionServerService.IServerService>, TransactionServerTester.TransactionServerService.IServerService {
        
        public ServerServiceClient() {
        }
        
        public ServerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public iExchange.Common.TransactionError Place(string tranXml, bool placeByRiskMonitor) {
            return base.Channel.Place(tranXml, placeByRiskMonitor);
        }
        
        public void PlaceByModel(Protocal.TransactionData tranData) {
            base.Channel.PlaceByModel(tranData);
        }
        
        public string Test() {
            return base.Channel.Test();
        }
        
        public string GetInitData(System.Guid[] accountIds) {
            return base.Channel.GetInitData(accountIds);
        }
    }
}
